export type ProjectId =
  | "forest-city"
  | "looking-for-growth"
  | "elevenlabs"
  | "amplitude"
  | "writing";

export type TabId = "all" | ProjectId;

export type Article = {
  title: string;
  url: string;
  outlet: string;
  logo: string;
  date: string;
  projects: ProjectId[];
};

export const tabs: { id: TabId; label: string; blurb?: string }[] = [
  { id: "all", label: "All" },
  {
    id: "forest-city",
    label: "Forest City",
    blurb:
      "I co-founded Forest City — a proposed city for one million people east of Cambridge.",
  },
  {
    id: "looking-for-growth",
    label: "Looking for Growth",
    blurb:
      "I co-founded Looking for Growth, a cross-party group of entrepreneurs pushing for housing, infrastructure, and growth.",
  },
  {
    id: "elevenlabs",
    label: "ElevenLabs",
    blurb: "I work on Growth at ElevenLabs.",
  },
  {
    id: "amplitude",
    label: "Amplitude",
    blurb:
      "I was an engineering manager and Head of AI at Amplitude, where I created and ran Amplitude's first engineering team outside North-America, and built Ask Amplitude.",
  },
  {
    id: "writing",
    label: "Writing",
    blurb:
      "Pieces I’ve written and recorded — CapX, the Forest City report, the ElevenLabs blog, Amplitude, and Latent Space.",
  },
];

const unsorted: Article[] = [
  {
    title: "I Met Britain’s Optimists in Kensington Gardens",
    url: "https://www.telegraph.co.uk/news/2026/09/06/optimistic-picnic-kensington-gardens-joe-reeve/",
    outlet: "The Telegraph",
    logo: "/press/telegraph.png",
    date: "2026-09-06",
    projects: ["looking-for-growth", "forest-city"],
  },
  {
    title: "How to build a city with Shiv Malik",
    url: "https://bradshawadvisory.com/insights/how-to-build-a-city-with-shiv-malik",
    outlet: "Bradshaw Advisory",
    logo: "/press/bradshaw.png",
    date: "2026-08-11",
    projects: ["forest-city"],
  },
  {
    title: "Episode 178: Forest City One",
    url: "https://easternpromise.podbean.com/e/episode-178-forest-city-one/",
    outlet: "Eastern Promise",
    logo: "/press/podbean.png",
    date: "2026-07-16",
    projects: ["forest-city"],
  },
  {
    title: "Government rules out backing new Cambridgeshire city ‘for now’",
    url: "https://www.newcivilengineer.com/latest/government-rules-out-backing-new-cambridgeshire-city-for-now-29-06-2026/",
    outlet: "New Civil Engineer",
    logo: "/press/newcivilengineer.png",
    date: "2026-06-29",
    projects: ["forest-city"],
  },
  {
    title: "It Only Sounds Mad Because We Think Small with Shiv Malik",
    url: "https://podcasts.apple.com/se/podcast/challenger-cities-ep90-it-only-sounds-mad-because-we/id1757715971?i=1000774681150&l=en-GB",
    outlet: "Challenger Cities",
    logo: "/press/applepodcasts.png",
    date: "2026-06-29",
    projects: ["forest-city"],
  },
  {
    title: "Forest City plans near Haverhill not backed by government",
    url: "https://www.burymercury.co.uk/news/26227508.forest-city-plans-near-haverhill-not-backed-government/",
    outlet: "Bury Mercury",
    logo: "/press/burymercury.png",
    date: "2026-06-26",
    projects: ["forest-city"],
  },
  {
    title:
      "Proposed new Cambridgeshire city would need metro system, SMR and desalination plant",
    url: "https://www.newcivilengineer.com/latest/proposed-new-cambridgeshire-city-would-need-metro-system-smr-and-desalination-plant-26-06-2026/",
    outlet: "New Civil Engineer",
    logo: "/press/newcivilengineer.png",
    date: "2026-06-26",
    projects: ["forest-city"],
  },
  {
    title: "New forest city still happening, says businessman",
    url: "https://www.bbc.co.uk/news/articles/c5yz4w1eggwo",
    outlet: "BBC",
    logo: "/press/bbc.png",
    date: "2026-06-25",
    projects: ["forest-city"],
  },
  {
    title: "We Are The Cavalry",
    url: "https://www.politicshome.com/news/article/we-cavalry-shiv-maliks-plans-build-new-city-near-cambridge",
    outlet: "PoliticsHome",
    logo: "/press/politicshome.png",
    date: "2026-06-24",
    projects: ["forest-city"],
  },
  {
    title: "The Great British Housing Crisis: Is a Brand New Mega-City the Answer?",
    url: "https://www.bbc.co.uk/sounds/play/m002xp88",
    outlet: "BBC Sounds",
    logo: "/press/bbc.png",
    date: "2026-06-18",
    projects: ["forest-city"],
  },
  {
    title: "Can robots build new towns — and other blue-sky thinking",
    url: "https://www.ft.com/content/445cd2ce-34e5-4572-bc97-38de08bebd01",
    outlet: "Financial Times",
    logo: "/press/ft.png",
    date: "2026-06-12",
    projects: ["forest-city"],
  },
  {
    title: "Forest City could define Burnham’s municipalism",
    url: "https://www.arguably.uk/p/forest-city-could-define-burnhams",
    outlet: "Arguably",
    logo: "/press/arguably.png",
    date: "2026-06-03",
    projects: ["forest-city"],
  },
  {
    title:
      "Forest City 1: a proposed new city for one million people and one of the most audacious planning ideas in modern Britain",
    url: "https://kts.org.uk/forest-city-1-a-proposed-new-city-for-one-million-people-audacious-or-outrageous/",
    outlet: "The Kingston Society",
    logo: "/press/kingstonsociety.png",
    date: "2026-06-03",
    projects: ["forest-city"],
  },
  {
    title: "Ambitious Cambridgeshire “Forest City” tests demand",
    url: "https://ukpropertyforums.com/ambitious-cambridgeshire-forest-city-tests-demand/",
    outlet: "UK Property Forums",
    logo: "/press/ukpropertyforums.png",
    date: "2026-06-01",
    projects: ["forest-city"],
  },
  {
    title: "A Forest City Today?",
    url: "https://www.bbc.co.uk/programmes/m002ww1p",
    outlet: "BBC Radio 4",
    logo: "/press/bbc.png",
    date: "2026-05-29",
    projects: ["forest-city"],
  },
  {
    title:
      "West Suffolk MP Nick Timothy launches formal campaign to fight proposed Forest City",
    url: "https://www.suffolknews.co.uk/haverhill/news/we-are-taking-the-campaign-to-the-next-level-opposition-t-9467777/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2026-05-29",
    projects: ["forest-city"],
  },
  {
    title:
      "Detailed report for proposed one million population Forest City sent to government",
    url: "https://www.suffolknews.co.uk/haverhill/news/government-receives-new-city-report-as-project-takes-shape-9462821/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2026-04-25",
    projects: ["forest-city"],
  },
  {
    title:
      "Vision for 400,000-home city set out with Community Land Trust-managed affordable housing",
    url: "https://www.insidehousing.co.uk/news/vision-for-400000-home-city-set-out-with-community-land-trust-managed-affordable-housing-96706",
    outlet: "Inside Housing",
    logo: "/press/insidehousing.png",
    date: "2026-04-20",
    projects: ["forest-city"],
  },
  {
    title: "Forest city eco-plan for 400,000 homes submitted to housing secretary",
    url: "https://www.planningresource.co.uk/article/1954875/forest-city-eco-plan-400000-homes-submitted-housing-secretary",
    outlet: "Planning Resource",
    logo: "/press/planningresource.png",
    date: "2026-04-16",
    projects: ["forest-city"],
  },
  {
    title: "Cambridge Challenges: Forest City",
    url: "https://cambridge105.co.uk/challenges-12-04-2026/",
    outlet: "Cambridge 105",
    logo: "/press/cambridge105.png",
    date: "2026-04-12",
    projects: ["forest-city"],
  },
  {
    title:
      "Forest city eco-plan for 400,000 new homes in East Anglia",
    url: "https://www.dailymail.com/news/article-15721383/Eden-Project-founder-100bn-forest-city-400000-homes-East-Anglia.html",
    outlet: "Daily Mail",
    logo: "/press/dailymail.png",
    date: "2026-04-10",
    projects: ["forest-city"],
  },
  {
    title: "Can These Brits Build a City?",
    url: "https://www.youtube.com/watch?v=R2RGRcIsoYk",
    outlet: "Looking for Growth",
    logo: "/press/lookingforgrowth.png",
    date: "2026-04-07",
    projects: ["forest-city", "looking-for-growth"],
  },
  {
    title:
      "West Suffolk MP and developers of proposed Forest City clash after meeting called off",
    url: "https://www.suffolknews.co.uk/newmarket/news/mp-and-new-city-creator-clash-over-meeting-postponement-9459881/",
    outlet: "Newmarket Journal",
    logo: "/press/suffolknews.png",
    date: "2026-04-02",
    projects: ["forest-city"],
  },
  {
    title:
      "Proposed Forest City criticised as ‘unaffordable’ and having ‘major flaws’",
    url: "https://www.suffolknews.co.uk/haverhill/news/proposed-new-city-described-as-having-major-flaws-and-as-b-9457924/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2026-03-19",
    projects: ["forest-city"],
  },
  {
    title: "10 ways that future urban living will be greener",
    url: "https://www.positive.news/society/10-ways-that-the-future-of-urban-living-will-be-greener/",
    outlet: "Positive News",
    logo: "/press/positivenews.png",
    date: "2026-03-17",
    projects: ["forest-city"],
  },
  {
    title: "Forest City proposals come under the spotlight",
    url: "https://www.suffolknews.co.uk/haverhill/news/forest-city-proposal-comes-under-the-spotlight-9455102/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2026-03-01",
    projects: ["forest-city"],
  },
  {
    title: "What will urban living look like in the future?",
    url: "https://www.positive.news/society/what-will-urban-living-look-like-in-the-future/",
    outlet: "Positive News",
    logo: "/press/positivenews.png",
    date: "2026-02-25",
    projects: ["forest-city"],
  },
  {
    title: "Why I’m scared of the YIMBYs",
    url: "https://www.thepathosofthings.com/p/why-im-scared-of-the-yimbys",
    outlet: "The Pathos of Things",
    logo: "/press/pathos.png",
    date: "2026-02-18",
    projects: ["forest-city"],
  },
  {
    title:
      "Creators of proposed Forest City 1 defend it in face of ‘recipe for disaster’ criticism",
    url: "https://www.suffolknews.co.uk/haverhill/news/it-is-completely-unrealistic-creators-of-forest-city-prop-9452925/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2026-02-11",
    projects: ["forest-city"],
  },
  {
    title: "Row breaks out over Forest City homes plans in Suffolk",
    url: "https://www.eadt.co.uk/news/25808519.row-breaks-forest-city-homes-plans-suffolk/",
    outlet: "East Anglian Daily Times",
    logo: "/press/eadt.png",
    date: "2026-02-02",
    projects: ["forest-city"],
  },
  {
    title: "S3 EP02 — Shiv Malik",
    url: "https://podcasts.apple.com/cz/podcast/s3-ep02-shiv-malik/id1710096268?i=1000746740415",
    outlet: "Superurbanism",
    logo: "/press/applepodcasts.png",
    date: "2026-01-26",
    projects: ["forest-city"],
  },
  {
    title:
      "Entrepreneur Shiv Malik defends plans for new forest city after West Suffolk MP launches petition",
    url: "https://www.suffolknews.co.uk/haverhill/news/a-huge-opportunity-for-change-entrepreneur-defends-plans-9449881/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2026-01-19",
    projects: ["forest-city"],
  },
  {
    title: "Taking a Chance: Planning, Housing and Positivity, 2026",
    url: "https://open.spotify.com/episode/1YRJcuPVJqVqhf5HuxJaE4",
    outlet: "Planning After Dark",
    logo: "/press/spotify.png",
    date: "2026-01-16",
    projects: ["forest-city"],
  },
  {
    title: "West Suffolk MP blasts Forest City proposals amid petition",
    url: "https://www.burymercury.co.uk/news/25766534.west-suffolk-mp-blasts-forest-city-proposals-amid-petition/",
    outlet: "Bury Mercury",
    logo: "/press/burymercury.png",
    date: "2026-01-15",
    projects: ["forest-city"],
  },
  {
    title: "Why the UK needs a new city",
    url: "https://www.spiked-online.com/2026/01/13/why-the-uk-needs-a-new-city/",
    outlet: "Spiked",
    logo: "/press/spiked.png",
    date: "2026-01-13",
    projects: ["forest-city"],
  },
  {
    title: "Paradise Found?",
    url: "https://futurecities.org.uk/2026/01/04/paradise-found/",
    outlet: "The Future Cities Project",
    logo: "/press/forestcity.png",
    date: "2026-01-04",
    projects: ["forest-city"],
  },
  {
    title:
      "Proposed Forest City Near Cambridge Sparks Debate Over Scale, Affordability and Long-Term Planning",
    url: "https://ukestates.uk/proposed-forest-city-near-cambridge-sparks-debate-over-scale-affordability-and-long-term-planning/",
    outlet: "UK Estates",
    logo: "/press/ukestates.png",
    date: "2025-12-23",
    projects: ["forest-city"],
  },
  {
    title: "New forest city is a rational plan, says architect",
    url: "https://www.bbc.co.uk/news/articles/cm2vgdxgd6vo",
    outlet: "BBC",
    logo: "/press/bbc.png",
    date: "2025-12-23",
    projects: ["forest-city"],
  },
  {
    title: "Forest City Proposal Challenges Conventional Urban Expansion",
    url: "https://archup.net/forest-city-proposal-suffolk-farmland-uk/",
    outlet: "ArchUp",
    logo: "/press/archup.png",
    date: "2025-12-23",
    projects: ["forest-city"],
  },
  {
    title: "NFB backs plans to build UK’s first new city in 50 years",
    url: "https://www.pbctoday.co.uk/news/projects/nfb-backs-plans-build-uks-first-new-city-in-50-years/158016/",
    outlet: "PBC Today",
    logo: "/press/pbctoday.png",
    date: "2025-12-22",
    projects: ["forest-city"],
  },
  {
    title:
      "Forest City 1 Can Change How the UK Thinks About Growth, Placemaking and Nature, According to the NFB",
    url: "https://constructuk.com/forest-city-1-can-change-how-the-uk-thinks-about-growth-placemaking-and-nature-according-to-the-nfb/",
    outlet: "Construct UK",
    logo: "/press/constructuk.png",
    date: "2025-12-22",
    projects: ["forest-city"],
  },
  {
    title: "Jackie Sadek on Forest City: ‘We need nothing short of market disruption’",
    url: "https://www.estatesgazette.co.uk/news/jackie-sadek-on-forest-city-we-need-nothing-short-of-market-disruption/",
    outlet: "Estates Gazette",
    logo: "/press/estatesgazette.png",
    date: "2025-12-18",
    projects: ["forest-city"],
  },
  {
    title: "Forest City’s first offline event in Cambridge",
    url: "https://cambridgetownowl.com/2025/12/10/forest-citys-first-offline-event-in-cambridge/",
    outlet: "Cambridge Town Owl",
    logo: "/press/cambridgetownowl.png",
    date: "2025-12-10",
    projects: ["forest-city"],
  },
  {
    title:
      "Gratte-ciels en bois, panneaux solaires et 6G : un projet de « ville-forêt »",
    url: "https://usbeketrica.com/fr/article/gratte-ciels-en-bois-panneaux-solaires-et-6g-au-royaume-uni-un-projet-de-ville-foret-peine-a-convaincre",
    outlet: "Usbek & Rica",
    logo: "/press/usbek.png",
    date: "2025-11-28",
    projects: ["forest-city"],
  },
  {
    title:
      "Why Did Millennials Choose Palestine Over Rent? — Shiv Malik on Building Britain’s First New City in 50 Years",
    url: "https://www.anglofuturism.co/p/why-did-millennials-choose-palestine",
    outlet: "Anglofuturism",
    logo: "/press/anglofuturism.png",
    date: "2025-11-27",
    projects: ["forest-city"],
  },
  {
    title:
      "Britain’s First New City in 50 Years: Shiv Malik on Building a Million-Person City East of Cambridge",
    url: "https://www.anglofuturism.co/p/britains-first-new-city-in-50-years",
    outlet: "Anglofuturism",
    logo: "/press/anglofuturism.png",
    date: "2025-11-22",
    projects: ["forest-city"],
  },
  {
    title:
      "Mind-boggling new £100bn city that looks straight out of a sci-fi film is coming to UK",
    url: "https://www.thesun.co.uk/news/37367353/new-forest-city-coming-to-uk-wooden-skyscrapers-housing/",
    outlet: "The Sun",
    logo: "/press/thesun.png",
    date: "2025-11-19",
    projects: ["forest-city"],
  },
  {
    title: "What about new forests, then?",
    url: "https://eastangliabylines.co.uk/environment/what-about-new-forests-then/",
    outlet: "East Anglia Bylines",
    logo: "/press/eabylines.png",
    date: "2025-11-19",
    projects: ["forest-city"],
  },
  {
    title:
      "Futuristic new UK city the size of Bristol with ‘skyscrapers made of wood’ to be built",
    url: "https://metro.co.uk/2025/11/18/futuristic-new-uk-city-size-bristol-skyscrapers-made-wood-built-24728205/",
    outlet: "Metro",
    logo: "/press/metro.png",
    date: "2025-11-18",
    projects: ["forest-city"],
  },
  {
    title: "Für rund eine Million Menschen: Eine innovative Waldstadt soll entstehen",
    url: "https://www.focus.de/panorama/welt/fuer-rund-eine-million-menschen-eine-innovative-waldstadt-soll-entstehen_0b483c02-688b-434a-9e38-df7a6e080f58.html",
    outlet: "Focus",
    logo: "/press/focus.png",
    date: "2025-11-17",
    projects: ["forest-city"],
  },
  {
    title: "Ambitious ‘Forest City 1’ Plan Near Cambridge Unveiled",
    url: "https://cambs-news.co.uk/ambitious-forest-city-1-plan-near-cambridge-unveiled/",
    outlet: "Cambs News",
    logo: "/press/cambsnews.png",
    date: "2025-11-17",
    projects: ["forest-city"],
  },
  {
    title: "‘Forest City’ proposed east of Cambridge for one million people",
    url: "https://www.cambridgeindependent.co.uk/news/forest-city-proposed-east-of-cambridge-for-one-million-peo-9441764/",
    outlet: "Cambridge Independent",
    logo: "/press/cambridgeindependent.png",
    date: "2025-11-14",
    projects: ["forest-city"],
  },
  {
    title:
      "Plans for new city between Haverhill and Newmarket questioned by community leaders",
    url: "https://www.suffolknews.co.uk/haverhill/news/plans-questioned-for-new-city-between-towns-that-could-house-9441623/",
    outlet: "Suffolk News",
    logo: "/press/suffolknews.png",
    date: "2025-11-14",
    projects: ["forest-city"],
  },
  {
    title:
      "Businessmen Shiv Malik and Joseph Reeve unveil plans for new forest city between Haverhill and Newmarket",
    url: "https://www.suffolknews.co.uk/haverhill/news/pair-unveil-plans-for-new-city-between-towns-that-could-hous-9440673/",
    outlet: "Haverhill Echo",
    logo: "/press/suffolknews.png",
    date: "2025-11-07",
    projects: ["forest-city"],
  },
  {
    title: "The progressive case for Anglofuturism",
    url: "https://www.newstatesman.com/ideas/2025/11/the-progressive-case-for-anglofuturism",
    outlet: "New Statesman",
    logo: "/press/newstatesman.png",
    date: "2025-11-04",
    projects: ["forest-city", "looking-for-growth"],
  },
  {
    title: "Forest city between Haverhill and Newmarket revealed",
    url: "https://www.burymercury.co.uk/news/25590164.forest-city-haverhill-newmarket-revealed/",
    outlet: "Bury Mercury",
    logo: "/press/burymercury.png",
    date: "2025-11-04",
    projects: ["forest-city"],
  },
  {
    title: "Forest city between Haverhill and Newmarket revealed",
    url: "https://www.eadt.co.uk/news/25590164.forest-city-haverhill-newmarket-revealed/",
    outlet: "East Anglian Daily Times",
    logo: "/press/eadt.png",
    date: "2025-11-04",
    projects: ["forest-city"],
  },
  {
    title: "Business pair reveal plans for affordable new city near Cambridge",
    url: "https://ukpropertyforums.com/business-pair-reveal-plans-for-affordable-new-city-near-cambridge/",
    outlet: "UK Property Forums",
    logo: "/press/ukpropertyforums.png",
    date: "2025-11-03",
    projects: ["forest-city"],
  },
  {
    title:
      "‘Bonkers’: the audacious plan for a 1mn-person city near Cambridge",
    url: "https://www.ft.com/content/e50ffbb3-45e7-4eb1-a82a-f7e93594d18f",
    outlet: "Financial Times",
    logo: "/press/ft.png",
    date: "2026-05-29",
    projects: ["forest-city"],
  },
  {
    title:
      "Vision for Forest City of one million people east of Cambridge sent to government",
    url: "https://www.cambridgeindependent.co.uk/news/vision-for-forest-city-of-one-million-people-east-of-cambrid-9463873/",
    outlet: "Cambridge Independent",
    logo: "/press/cambridgeindependent.png",
    date: "2026-04-30",
    projects: ["forest-city"],
  },
  {
    title:
      "Cambridge doesn’t need new homes – it needs a new city",
    url: "https://capx.co/cambridge-doesnt-need-new-homes-it-needs-a-new-city",
    outlet: "CapX",
    logo: "/press/capx.png",
    date: "2026-04-20",
    projects: ["forest-city", "writing"],
  },
  {
    title:
      "New Forest City report pitches 400,000-home settlement to government",
    url: "https://www.housingtoday.co.uk/news/new-forest-city-report-pitches-400000-home-settlement-to-government/5141783.article",
    outlet: "Housing Today",
    logo: "/press/housingtoday.png",
    date: "2026-04-15",
    projects: ["forest-city"],
  },
  {
    title: "Eden Project founder backs plan for new city in East Anglia",
    url: "https://www.telegraph.co.uk/business/2026/04/09/eden-project-founder-backs-plan-for-new-city-in-east-anglia/",
    outlet: "The Telegraph",
    logo: "/press/telegraph.png",
    date: "2026-04-09",
    projects: ["forest-city"],
  },
  {
    title: "ElevenLabs is now a Kiro Power",
    url: "https://elevenlabs.io/blog/elevenlabs-is-now-a-kiro-power",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2026-04-08",
    projects: ["elevenlabs", "writing"],
  },
  {
    title: "Scribe v2 just got an upgrade",
    url: "https://elevenlabs.io/blog/scribe-v2-just-got-an-upgrade",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2026-04-02",
    projects: ["elevenlabs", "writing"],
  },
  {
    title: "Text to Speech API — up to 40% faster globally",
    url: "https://elevenlabs.io/blog/text-to-speech-api-up-to-40-faster-globally",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2026-02-20",
    projects: ["elevenlabs", "writing"],
  },
  {
    title:
      "Talk to a Statue: building a multi-modal ElevenAgents-powered app",
    url: "https://elevenlabs.io/blog/talk-to-a-statue-building-a-multi-modal-elevenagents-powered-app",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2026-02-18",
    projects: ["elevenlabs", "writing"],
  },
  {
    title: "How to talk to statues",
    url: "https://ai.engineer/talks/how-to-talk-to-statues-joe-reeve-elevenlabs",
    outlet: "AI Engineer",
    logo: "/press/aiengineer.png",
    date: "2026-02-10",
    projects: ["elevenlabs"],
  },
  {
    title: "Eleven v3 is now generally available",
    url: "https://elevenlabs.io/blog/eleven-v3-is-now-generally-available",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2026-02-02",
    projects: ["elevenlabs", "writing"],
  },
  {
    title: "Introducing the ElevenLabs × Lovable integration",
    url: "https://elevenlabs.io/blog/introducing-the-elevenlabs-lovable-integration",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2025-12-16",
    projects: ["elevenlabs", "writing"],
  },
  {
    title:
      "ElevenLabs OSS Engineers Fund — supporting the open-source projects that shape our work",
    url: "https://elevenlabs.io/blog/elevenlabs-oss-engineers-fund-supporting-the-open-source-projects-that-shape-our-work",
    outlet: "ElevenLabs",
    logo: "/press/elevenlabs.svg",
    date: "2025-12-15",
    projects: ["elevenlabs", "writing"],
  },
  {
    title:
      "The UK’s ‘Abundance’ movement pushes for housing, infrastructure, optimism",
    url: "https://www.bloomberg.com/news/articles/2025-11-28/the-uk-s-abundance-movement-pushes-for-housing-infrastructure-optimism",
    outlet: "Bloomberg",
    logo: "/press/bloomberg.png",
    date: "2025-11-28",
    projects: ["looking-for-growth", "forest-city"],
  },
  {
    title: "How ambitious ‘forest city’ plan for England could become a reality",
    url: "https://www.theguardian.com/environment/2025/nov/23/how-ambitious-forest-city-plan-for-england-could-become-a-reality",
    outlet: "The Guardian",
    logo: "/press/guardian.png",
    date: "2025-11-23",
    projects: ["forest-city"],
  },
  {
    title: "A vast new city for 1 million people is being planned for the UK",
    url: "https://www.timeout.com/uk/news/a-vast-new-city-for-one-million-people-is-being-planned-for-the-uk-112325",
    outlet: "Time Out",
    logo: "/press/timeout.png",
    date: "2025-11-23",
    projects: ["forest-city"],
  },
  {
    title:
      "‘Bonkers’ plan to build brand new city for one million people",
    url: "https://www.telegraph.co.uk/business/2025/11/15/bonkers-plan-to-build-brand-new-city-for-one-million-people/",
    outlet: "The Sunday Telegraph",
    logo: "/press/telegraph.png",
    date: "2025-11-15",
    projects: ["forest-city"],
  },
  {
    title:
      "Plans revealed for Forest City on Suffolk and Cambridgeshire farmland",
    url: "https://www.farmersguide.co.uk/business/planning-buildings/plans-revealed-for-forest-city-on-suffolk-and-cambridgeshire-farmland/",
    outlet: "Farmers Guide",
    logo: "/press/farmersguide.png",
    date: "2025-11-06",
    projects: ["forest-city"],
  },
  {
    title:
      "Garden city could become UK’s first new city in half a century",
    url: "https://www.independent.co.uk/news/uk/home-news/garden-city-plans-suffolk-cambridge-london-b2856038.html",
    outlet: "The Independent",
    logo: "/press/independent.png",
    date: "2025-10-31",
    projects: ["forest-city"],
  },
  {
    title: "New city on Suffolk and Cambridgeshire border proposed",
    url: "https://www.bbc.co.uk/news/articles/cjw97nlq8q7o",
    outlet: "BBC",
    logo: "/press/bbc.png",
    date: "2025-10-30",
    projects: ["forest-city"],
  },
  {
    title: "Boys and their toys",
    url: "https://www.economist.com/britain/2025/10/29/blighty-newsletter-boys-and-their-toys",
    outlet: "The Economist",
    logo: "/press/economist.png",
    date: "2025-10-29",
    projects: ["forest-city"],
  },
  {
    title: "How to build Britain’s next great city",
    url: "https://capx.co/how-to-build-britains-next-great-city",
    outlet: "CapX",
    logo: "/press/capx.png",
    date: "2025-10-24",
    projects: ["forest-city", "writing"],
  },
  {
    title: "Britain needs a building boom: here’s how we make it happen",
    url: "https://capx.co/britain-needs-a-building-boom-heres-how-we-make-it-happen",
    outlet: "CapX",
    logo: "/press/capx.png",
    date: "2025-01-16",
    projects: ["looking-for-growth", "writing"],
  },
  {
    title: "We Can Build a City",
    url: "https://www.forestcity.uk/report",
    outlet: "Forest City",
    logo: "/press/forestcity.png",
    date: "2025-10-23",
    projects: ["forest-city", "writing"],
  },
  {
    title:
      "The campaign to build a UK city with a million residents by 2035",
    url: "https://www.thetimes.com/life-style/property-home/article/forest-city-plan-one-million-residents-2035-2mp9fjjzv",
    outlet: "The Times",
    logo: "/press/times.png",
    date: "2025-12-16",
    projects: ["forest-city"],
  },
  {
    title: "Who's behind London's vigilante tube cleaners?",
    url: "https://www.londoncentric.media/p/looking-for-growth-bakerloo-line-graffiti-dominic-cummings",
    outlet: "London Centric",
    logo: "/press/londoncentric.png",
    date: "2025-07-01",
    projects: ["looking-for-growth"],
  },
  {
    title:
      "Volunteer graffiti cleaners, in Charlotte Ivers’ column",
    url: "https://www.thetimes.com/comment/columnists/article/big-bureaucracy-knows-the-real-enemies-volunteer-graffiti-cleaners-f995lk2wq",
    outlet: "The Sunday Times",
    logo: "/press/times.png",
    date: "2025-07-06",
    projects: ["looking-for-growth"],
  },
  {
    title: "Volunteers removing graffiti from Bakerloo line Tube trains",
    url: "https://www.standard.co.uk/news/london/group-graffiti-plagued-bakerloo-line-trains-london-sadiq-khan-b1231831.html",
    outlet: "The London Standard",
    logo: "/press/standard.png",
    date: "2025-06-09",
    projects: ["looking-for-growth"],
  },
  {
    title: "Looking for Growth",
    url: "https://en.wikipedia.org/wiki/Looking_for_Growth",
    outlet: "Wikipedia",
    logo: "/press/wikipedia.png",
    date: "2025-11-01",
    projects: ["looking-for-growth"],
  },
  {
    title: "From RLHF to RLHB: the case for learning from human behaviour",
    url: "https://www.latent.space/p/amplitude",
    outlet: "Latent Space",
    logo: "/press/latentspace.png",
    date: "2023-06-08",
    projects: ["writing", "amplitude"],
  },
  {
    title: "The Story of Ask Amplitude",
    url: "https://amplitude.com/blog/ask-amplitude",
    outlet: "Amplitude",
    logo: "/press/amplitude.png",
    date: "2023-08-08",
    projects: ["writing", "amplitude"],
  },
  {
    title: "How AI improves development processes for software engineers",
    url: "https://www.sdxcentral.com/analysis/how-ai-improves-development-processes-for-software-engineers/",
    outlet: "SDxCentral",
    logo: "/press/sdxcentral.png",
    date: "2024-04-01",
    projects: ["amplitude"],
  },
  {
    title: "Could artificial intelligence benefit democracy?",
    url: "https://www.bbc.co.uk/news/uk-politics-68627916",
    outlet: "BBC",
    logo: "/press/bbc.png",
    date: "2024-03-29",
    projects: [],
  },
  {
    title:
      "Developers are embracing AI-enabled tools. Here's how that's changing the way they code",
    url: "https://siliconangle.com/2023/10/22/developers-embracing-ai-enabled-tools-heres-thats-changing-way-code/",
    outlet: "SiliconANGLE",
    logo: "/press/siliconangle.png",
    date: "2023-10-22",
    projects: [],
  },
  {
    title: "Data-driven AI as the future of product innovation",
    url: "https://telcomagazine.com/articles/data-driven-ai-as-the-future-of-product-innovation",
    outlet: "Telco Magazine",
    logo: "/press/telcomagazine.png",
    date: "2023-08-14",
    projects: ["amplitude"],
  },
  {
    title:
      "Amplitude adds AI features to simplify business intelligence queries and data governance",
    url: "https://siliconangle.com/2023/08/10/amplitude-adds-ai-features-simplify-bi-queries-data-governance/",
    outlet: "SiliconANGLE",
    logo: "/press/siliconangle.png",
    date: "2023-08-10",
    projects: ["amplitude"],
  },
  {
    title: "Dissecting the AI Hype with Amplitude’s Joseph Reeve",
    url: "https://em360tech.com/tech-articles/dissecting-ai-hype-amplitudes-joseph-reeve",
    outlet: "EM360",
    logo: "/press/em360.png",
    date: "2023-07-04",
    projects: ["amplitude"],
  },
  {
    title: "Your AI coding assistant is a hot mess",
    url: "https://www.techmonitor.ai/digital-economy/ai-and-automation/your-ai-coding-assistant-is-a-hot-mess",
    outlet: "Tech Monitor",
    logo: "/press/techmonitor.png",
    date: "2023-06-19",
    projects: ["amplitude"],
  },
  {
    title: "How to talk to statues",
    url: "https://www.youtube.com/watch?v=u-rJwPPU3QA",
    outlet: "YouTube",
    logo: "/press/youtube.png",
    date: "2026-02-10",
    projects: ["elevenlabs"],
  },
  {
    title: "Meet the techno-optimists hoping to save the world",
    url: "https://www.spectator.co.uk/article/nationalise-google-the-techno-optimists-hoping-to-save-the-world/",
    outlet: "The Spectator",
    logo: "/press/spectator.png",
    date: "2021-06-01",
    projects: [],
  },
  {
    title:
      "The Wikipedia of COVID-19 has launched a crowdfunding drive to keep going",
    url: "https://techcrunch.com/2020/04/27/the-wikipedia-of-covid-19-has-launched-a-crowdfunding-drive-to-keep-going/",
    outlet: "TechCrunch",
    logo: "/press/techcrunch.png",
    date: "2020-04-27",
    projects: [],
  },
  {
    title: "Technologists Are Crowdsourcing a Coronavirus Handbook",
    url: "https://gizmodo.com/technologists-are-crowdsourcing-a-coronavirus-handbook-1842291959",
    outlet: "Gizmodo",
    logo: "/press/gizmodo.svg",
    date: "2020-03-16",
    projects: [],
  },
];

export const articles = [...unsorted].sort((a, b) =>
  a.date < b.date ? 1 : a.date > b.date ? -1 : 0,
);

export function formatDate(iso: string) {
  const [year, month, day] = iso.split("-").map(Number);
  return new Date(Date.UTC(year, month - 1, day)).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });
}
